### ISSUE TITLE
favicon not found

### ISSUE THREAD

**Issue by siznax** [siznax/moo#31]
INFO:werkzeug:127.0.0.1 - - [01/Jun/2021 15:38:07] "GET /favicon.ico HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/Werkzeug-2.0.1-py3.9.egg/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by siznax** [comment]
Fixed with 9e8e40676bec6d242a8fce0f61a31c4199b85d10
