### ISSUE TITLE
TypeError: page_not_found() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by siznax** [siznax/moo#32]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
TypeError: page_not_found() takes 0 positional arguments but 1 was given

**Comment by siznax** [comment]
Fixed with 90cb1eae31addadd30328f95549d276c625ad15b
