### ISSUE TITLE
IndexError when HISTORY empty

### ISSUE THREAD

**Issue by siznax** [siznax/moo#35]
```
IndexError: list index out of range

Traceback (most recent call last)
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/site-packages/Flask-2.0.1-py3.9.egg/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/Users/harold/sw/moo/Moo/play/app.py", line 228, in history
return serve_album(ind[0], ind, alb)
IndexError: list index out of range
```

**Comment by siznax** [comment]
Fixed with v0.4
